services:
  app:
    image: ghcr.io/csyqlz/vozeb:latest
    container_name: vozeb
    ports:
      - "3000:3000"
    volumes:
      - vozeb-data:/app/web/.data
    restart: unless-stopped

volumes:
  vozeb-data:
