services:
  app:
    image: ghcr.io/csyqlz/vozeb:latest
    ports:
      - "3000:3000"
    volumes:
      - vozeb-data:/app/web/.data
    mem_limit: 512m
    memswap_limit: 768m
    restart: unless-stopped

volumes:
  vozeb-data:
